name: e_barangay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  image_picker: ^1.2.1
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
